language: go

go:
  - "1.9"

script:  make
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - db-cli.zip
    - db-cli
    - db-cli_osx
    - db-cli.exe
  skip_cleanup: true
  on:
    tags: true